name: data
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - postprocess.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.lzg.nrw.de/covid19/daten/covid19_5966.csv
          downloaded_filename: data.csv
          postprocess: postprocess.js
